version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: spring-template-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: spring_template
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7.0
    container_name: spring-template-redis
    ports:
      - "6379:6379"

volumes:
  mysql_data: 