version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: diary-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: diary
      MYSQL_USER: diary
      MYSQL_PASSWORD: diary
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0
    container_name: spring-template-redis
    ports:
      - "6379:6379"

volumes:
  mysql_data:
    name: diary_mysql_data
