name: Security

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정(UTC)에 실행

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Java 23 설정 (메인 서비스용)
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: 'gradle'

      # Gradle 권한 설정
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 기존 보안 검사 작업들...

      # Java 17 설정 (Dependency Check용)
      - name: Set up JDK 17 for Dependency Check
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Dependency Check 실행
      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'Diary API'
          path: '.'
          format: 'HTML'
          out: 'reports'
          args: '--failOnCVSS 7 --enableRetired'
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}

      # 결과 리포트 업로드
      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: dependency-check-report
          path: reports/ 